/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnlockRouteImport } from './routes/unlock'
import { Route as GatedRouteImport } from './routes/_gated'
import { Route as GatedIndexRouteImport } from './routes/_gated.index'
import { Route as GatedLiveRouteImport } from './routes/_gated.live'

const UnlockRoute = UnlockRouteImport.update({
  id: '/unlock',
  path: '/unlock',
  getParentRoute: () => rootRouteImport,
} as any)
const GatedRoute = GatedRouteImport.update({
  id: '/_gated',
  getParentRoute: () => rootRouteImport,
} as any)
const GatedIndexRoute = GatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GatedRoute,
} as any)
const GatedLiveRoute = GatedLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => GatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof GatedIndexRoute
  '/unlock': typeof UnlockRoute
  '/live': typeof GatedLiveRoute
}
export interface FileRoutesByTo {
  '/unlock': typeof UnlockRoute
  '/live': typeof GatedLiveRoute
  '/': typeof GatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_gated': typeof GatedRouteWithChildren
  '/unlock': typeof UnlockRoute
  '/_gated/live': typeof GatedLiveRoute
  '/_gated/': typeof GatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/unlock' | '/live'
  fileRoutesByTo: FileRoutesByTo
  to: '/unlock' | '/live' | '/'
  id: '__root__' | '/_gated' | '/unlock' | '/_gated/live' | '/_gated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  GatedRoute: typeof GatedRouteWithChildren
  UnlockRoute: typeof UnlockRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unlock': {
      id: '/unlock'
      path: '/unlock'
      fullPath: '/unlock'
      preLoaderRoute: typeof UnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_gated': {
      id: '/_gated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_gated/': {
      id: '/_gated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof GatedIndexRouteImport
      parentRoute: typeof GatedRoute
    }
    '/_gated/live': {
      id: '/_gated/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof GatedLiveRouteImport
      parentRoute: typeof GatedRoute
    }
  }
}

interface GatedRouteChildren {
  GatedLiveRoute: typeof GatedLiveRoute
  GatedIndexRoute: typeof GatedIndexRoute
}

const GatedRouteChildren: GatedRouteChildren = {
  GatedLiveRoute: GatedLiveRoute,
  GatedIndexRoute: GatedIndexRoute,
}

const GatedRouteWithChildren = GatedRoute._addFileChildren(GatedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  GatedRoute: GatedRouteWithChildren,
  UnlockRoute: UnlockRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
